- hosts: zvm2

  collections:
    - ibm.ibm_zos_core

  gather_facts: no

  environment: "{{ environment_vars }}"
  vars_files: 
    - "host_vars/cicd_artifacts.yml"

  tasks:

    #Delete generated dbds
    - name: delete a data set
      zos_data_set:
        name: IMSTESTU.ANSI.DBDLIB2({{ item }})
        state: absent
        type: MEMBER
      loop: '{{ dbds }}'

    #Delete generated psbs
    - name: delete a data set
      zos_data_set:
        name: IMSTESTU.ANSI.PSBLIB2({{ item }})
        state: absent
        type: MEMBER
      loop: '{{ psbs }}'

    #Delete generated acbs
    # - name: delete a data set
    #   zos_data_set:
    #     name: IMSTESTU.ANSI.ACBLIB1({{ item }})
    #     state: absent
    #     type: MEMBER
    #   loop: '{{ acbs }}'

   
